In [3]:
import pandas as pd
import numpy as np
import requests
# from bs4 import BeautifulSoup as bs
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
import time

In [4]:
user_rating = []
review_date = []
review_title = []
review = []
likes = []
dislikes = []

url = 'https://www.imdb.com/title/tt18923754/reviews/?ref_=tt_ov_ql_2'
# option = webdriver.ChromeOptions()
# option.add_argument("headless")
driver = webdriver.Chrome()
driver.get(url)

see_all = driver.find_element(By.XPATH, '//*[@id="__next"]/main/div/section/div/section/div/div[1]/section[1]/div[3]/div/span[2]/button')

while True:
    try:
        see_all.send_keys(Keys.ENTER)
        # time.sleep(120)
    except Exception as e:
        break

for i in range(1,450):
    try:
        rating =  driver.find_element(By.XPATH, '//*[@id="__next"]/main/div/section/div/section/div/div[1]/section[1]/article[{}]/div[1]/div[1]/div[1]/span/span[1]'.format(1*i)).text
        date = driver.find_element(By.XPATH, '//*[@id="__next"]/main/div/section/div/section/div/div[1]/section[1]/article[{}]/div[2]/ul/li[2]'.format(1*i)).text
        title = driver.find_element(By.XPATH, '//*[@id="__next"]/main/div/section/div/section/div/div[1]/section[1]/article[{}]/div[1]/div[1]/div[2]/div/a/h3'.format(1*i)).text
        review_content = driver.find_element(By.XPATH, '//*[@id="__next"]/main/div/section/div/section/div/div[1]/section[1]/article[{}]/div[1]/div[1]/div[3]/div/div/div'.format(1*i)).text
        like = driver.find_element(By.XPATH, '//*[@id="__next"]/main/div/section/div/section/div/div[1]/section[1]/article[{}]/div[1]/div[2]/div[1]/div/span[1]/span[3]'.format(1*i)).text
        dislike = driver.find_element(By.XPATH, '//*[@id="__next"]/main/div/section/div/section/div/div[1]/section[1]/article[{}]/div[1]/div[2]/div[1]/div/span[2]/span'.format(1*i)).text

        user_rating.append(rating)
        review_date.append(date)
        review_title.append(title)
        review.append(review_content)
        likes.append(like)
        dislikes.append(dislike)

    except:
        continue

In [5]:
print(len(user_rating), len(review_date), len(review_title),  len(review), len(likes), len(dislikes))

307 307 307 307 307 307

In [6]:
daredevil_born_sentiment_raw = {'User_Ratings': user_rating, 
                           'Review_Dates': review_date,
                           'Titles': review_title,
                           'Reviews': review,
                           'Likes': likes,
                           'Dislikes': dislikes}

daredevil_born_sentiment_df = pd.DataFrame(daredevil_born_sentiment_raw)

In [7]:
daredevil_born_sentiment_df

,User_Ratings,Review_Dates,Titles,Reviews,Likes,Dislikes
0,9,"Aug 9, 2025",Daredevil is back,I can't tell you how glad I am that Daredevil ...,71,1
1,8,"Jul 11, 2025",Solid revival,Daredevil: Born Again was announced several ye...,54,3
2,10,"Aug 9, 2025",Fantastic,I don't even know where to begin in describing...,66,3
3,9,"Jul 26, 2025",call Rome,Historians of the far future looking back at o...,48,3
4,8,"Jul 6, 2025",A Solid Return for the Devil of Hell's Kitchen,This spiritual sequel doesn't try to be Season...,48,3
...,...,...,...,...,...,...
302,4,"Apr 18, 2025",An insult to Netflix's D.D.,A huge disappointment after waiting a long tim...,3,3
303,5,"Apr 20, 2025",Very Meh...Very Disney,"Overall, it was just ok. Nowhere near as good ...",7,13
304,5,"Mar 6, 2025",S tier Marvel,Okay i am a Marvel Comic Book fan that has bee...,9,23
305,3,"Apr 21, 2025",Clearly not the Netflix version.,Poorly written without loyalty to the true cha...,6,13
306,4,"Apr 18, 2025",Lukewarm wannabe.,While this new thing was airing I had to go ba...,4,7

In [8]:
daredevil_born_sentiment_clean_df = daredevil_born_sentiment_df.drop_duplicates()

daredevil_born_sentiment_clean_df

,User_Ratings,Review_Dates,Titles,Reviews,Likes,Dislikes
0,9,"Aug 9, 2025",Daredevil is back,I can't tell you how glad I am that Daredevil ...,71,1
1,8,"Jul 11, 2025",Solid revival,Daredevil: Born Again was announced several ye...,54,3
2,10,"Aug 9, 2025",Fantastic,I don't even know where to begin in describing...,66,3
3,9,"Jul 26, 2025",call Rome,Historians of the far future looking back at o...,48,3
4,8,"Jul 6, 2025",A Solid Return for the Devil of Hell's Kitchen,This spiritual sequel doesn't try to be Season...,48,3
...,...,...,...,...,...,...
302,4,"Apr 18, 2025",An insult to Netflix's D.D.,A huge disappointment after waiting a long tim...,3,3
303,5,"Apr 20, 2025",Very Meh...Very Disney,"Overall, it was just ok. Nowhere near as good ...",7,13
304,5,"Mar 6, 2025",S tier Marvel,Okay i am a Marvel Comic Book fan that has bee...,9,23
305,3,"Apr 21, 2025",Clearly not the Netflix version.,Poorly written without loyalty to the true cha...,6,13
306,4,"Apr 18, 2025",Lukewarm wannabe.,While this new thing was airing I had to go ba...,4,7

In [9]:
daredevil_born_sentiment_clean_df['Series'] = "Daredevil: Born Again"
daredevil_born_sentiment_clean_df['Network'] = "Disney+"

daredevil_born_sentiment_clean_df

,User_Ratings,Review_Dates,Titles,Reviews,Likes,Dislikes,Series,Network
0,9,"Aug 9, 2025",Daredevil is back,I can't tell you how glad I am that Daredevil ...,71,1,Daredevil: Born Again,Disney+
1,8,"Jul 11, 2025",Solid revival,Daredevil: Born Again was announced several ye...,54,3,Daredevil: Born Again,Disney+
2,10,"Aug 9, 2025",Fantastic,I don't even know where to begin in describing...,66,3,Daredevil: Born Again,Disney+
3,9,"Jul 26, 2025",call Rome,Historians of the far future looking back at o...,48,3,Daredevil: Born Again,Disney+
4,8,"Jul 6, 2025",A Solid Return for the Devil of Hell's Kitchen,This spiritual sequel doesn't try to be Season...,48,3,Daredevil: Born Again,Disney+
...,...,...,...,...,...,...,...,...
302,4,"Apr 18, 2025",An insult to Netflix's D.D.,A huge disappointment after waiting a long tim...,3,3,Daredevil: Born Again,Disney+
303,5,"Apr 20, 2025",Very Meh...Very Disney,"Overall, it was just ok. Nowhere near as good ...",7,13,Daredevil: Born Again,Disney+
304,5,"Mar 6, 2025",S tier Marvel,Okay i am a Marvel Comic Book fan that has bee...,9,23,Daredevil: Born Again,Disney+
305,3,"Apr 21, 2025",Clearly not the Netflix version.,Poorly written without loyalty to the true cha...,6,13,Daredevil: Born Again,Disney+
306,4,"Apr 18, 2025",Lukewarm wannabe.,While this new thing was airing I had to go ba...,4,7,Daredevil: Born Again,Disney+

In [10]:
daredevil_born_sentiment_clean_df.to_csv('daredevil_born_again_sentiment.csv')